/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.KeyEvent;
import java.sql.*;
/**
 *
 * @author Ajinkya
 */
public class MBAQuestionnaire extends javax.swing.JFrame {
    
    
   
    
    public static String prn,prn1,prn2,prn3,prn4,prn5,prn6,prn7;
    public static String question1,question2,question3,question4,question5,question6,question7,question8;
    public static String response1,response2,response3,response4,response5,response6,response7,response8;
           
    private static final String CONN_STRING= "jdbc:mysql://localhost:3306/sefs";
    
    
    /**
     * Creates new form MBAQuestionnaire
     */
    public MBAQuestionnaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mba1 = new javax.swing.ButtonGroup();
        mba2 = new javax.swing.ButtonGroup();
        mba3 = new javax.swing.ButtonGroup();
        mba4 = new javax.swing.ButtonGroup();
        mba5 = new javax.swing.ButtonGroup();
        mba6 = new javax.swing.ButtonGroup();
        mba7 = new javax.swing.ButtonGroup();
        mba8 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        t5 = new javax.swing.JLabel();
        t6 = new javax.swing.JLabel();
        t7 = new javax.swing.JLabel();
        t8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rb1 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        rb7 = new javax.swing.JRadioButton();
        rb8 = new javax.swing.JRadioButton();
        rb9 = new javax.swing.JRadioButton();
        rb10 = new javax.swing.JRadioButton();
        rb11 = new javax.swing.JRadioButton();
        rb12 = new javax.swing.JRadioButton();
        rb13 = new javax.swing.JRadioButton();
        rb14 = new javax.swing.JRadioButton();
        rb15 = new javax.swing.JRadioButton();
        rb16 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        tb = new javax.swing.JTextField();
        rb2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Feedback Questions");

        t1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t1.setText("1.Was The Syllabus Covered Well Before Exams?");

        t2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t2.setText("2.Are You Satisfied With Entire Cource Design?");

        t3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t3.setText("3.Are you Satisfied With Overall Knowledge of Faculty?");

        t4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t4.setText("4.Do You Feel the cirriculam is Good?");

        t5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t5.setText("5.Are the Students Able to Cope up with Speed of Teaching?");

        t6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t6.setText("6.Are Moodle Exams Conducted Regularly");

        t7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t7.setText("7.Do you Like The 60% Internal and 40% External Pattern in College?");

        t8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t8.setText("8.Are you comfotable with College Timings?");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mba1.add(rb1);
        rb1.setText("Yes");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        mba2.add(rb3);
        rb3.setText("Yes");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });

        mba2.add(rb4);
        rb4.setText("No");
        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4ActionPerformed(evt);
            }
        });

        mba3.add(rb5);
        rb5.setText("Yes");
        rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5ActionPerformed(evt);
            }
        });

        mba3.add(rb6);
        rb6.setText("No");
        rb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6ActionPerformed(evt);
            }
        });

        mba4.add(rb7);
        rb7.setText("Yes");
        rb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb7ActionPerformed(evt);
            }
        });

        mba4.add(rb8);
        rb8.setText("No");
        rb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb8ActionPerformed(evt);
            }
        });

        mba5.add(rb9);
        rb9.setText("Yes");
        rb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb9ActionPerformed(evt);
            }
        });

        mba5.add(rb10);
        rb10.setText("No");
        rb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb10ActionPerformed(evt);
            }
        });

        mba6.add(rb11);
        rb11.setText("Yes");
        rb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb11ActionPerformed(evt);
            }
        });

        mba6.add(rb12);
        rb12.setText("No");
        rb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb12ActionPerformed(evt);
            }
        });

        mba7.add(rb13);
        rb13.setText("Yes");
        rb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb13ActionPerformed(evt);
            }
        });

        mba7.add(rb14);
        rb14.setText("No");
        rb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb14ActionPerformed(evt);
            }
        });

        mba8.add(rb15);
        rb15.setText("Yes");
        rb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb15ActionPerformed(evt);
            }
        });

        mba8.add(rb16);
        rb16.setText("No");
        rb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb16ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("PRN : ");

        tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbActionPerformed(evt);
            }
        });
        tb.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbPropertyChange(evt);
            }
        });
        tb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbKeyTyped(evt);
            }
        });

        mba1.add(rb2);
        rb2.setText("No");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb5)
                                .addGap(18, 18, 18)
                                .addComponent(rb6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb7)
                                .addGap(18, 18, 18)
                                .addComponent(rb8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb9)
                                .addGap(18, 18, 18)
                                .addComponent(rb10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb11)
                                .addGap(18, 18, 18)
                                .addComponent(rb12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb13)
                                .addGap(18, 18, 18)
                                .addComponent(rb14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb15)
                                .addGap(18, 18, 18)
                                .addComponent(rb16))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(rb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb4)
                                    .addComponent(rb2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(tb, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1)
                    .addComponent(rb1)
                    .addComponent(rb2))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2)
                    .addComponent(rb3)
                    .addComponent(rb4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb5)
                    .addComponent(rb6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t4)
                    .addComponent(rb7)
                    .addComponent(rb8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t5)
                    .addComponent(rb9)
                    .addComponent(rb10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t6)
                    .addComponent(rb11)
                    .addComponent(rb12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t7)
                    .addComponent(rb13)
                    .addComponent(rb14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t8)
                    .addComponent(rb15)
                    .addComponent(rb16))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        
        prn=tb.getText();
        prn1=tb.getText();
        prn2=tb.getText();
        prn3=tb.getText();
        prn4=tb.getText();
        prn5=tb.getText();
        prn6=tb.getText();
        prn7=tb.getText();
    
         question1=t1.getText();
         question2=t2.getText();
         question3=t3.getText();
         question4=t4.getText();
         question5=t5.getText();
         question6=t6.getText();
         question7=t7.getText();
         question8=t8.getText();
      
         response1=mba1.getSelection().getActionCommand();
         response2=mba2.getSelection().getActionCommand();
         response3=mba3.getSelection().getActionCommand();
         response4=mba4.getSelection().getActionCommand();
         response5=mba5.getSelection().getActionCommand();
         response6=mba6.getSelection().getActionCommand();
         response7=mba7.getSelection().getActionCommand();
         response8=mba8.getSelection().getActionCommand();
         
         
         
         
         
          
           Connection conn = null;
        try{     
            conn = DriverManager.getConnection(CONN_STRING, "root" , "");
            System.out.println("Done Dona Done Done "); 
            Statement stm=(Statement) conn.createStatement();
             String insert="INSERT INTO `response`(`PRN`, `Question`, `Response`) VALUES ('"+prn+"','"+question1+"','"+response1+"')";
               String insert1="INSERT INTO `response`(`PRN`, `Question`, `Response`) VALUES ('"+prn1+"','"+question2+"','"+response2+"')";
      String insert2="INSERT INTO `response`(`PRN`, `Question`, `Response`) VALUES ('"+prn2+"','"+question3+"','"+response3+"')";
      String insert3="INSERT INTO `response`(`PRN`, `Question`, `Response`) VALUES ('"+prn3+"','"+question4+"','"+response4+"')";
      String insert4="INSERT INTO `response`(`PRN`, `Question`, `Response`) VALUES ('"+prn4+"','"+question5+"','"+response5+"')";
      String insert5="INSERT INTO `response`(`PRN`, `Question`, `Response`) VALUES ('"+prn5+"','"+question6+"','"+response6+"')";
      String insert6="INSERT INTO `response`(`PRN`, `Question`, `Response`) VALUES ('"+prn6+"','"+question7+"','"+response7+"')";
      String insert7="INSERT INTO `response`(`PRN`, `Question`, `Response`) VALUES ('"+prn7+"','"+question8+"','"+response8+"')";
    
            stm.executeUpdate(insert);
            stm.executeUpdate(insert1);
            stm.executeUpdate(insert2);
            stm.executeUpdate(insert3);
            stm.executeUpdate(insert4);
            stm.executeUpdate(insert5);
            stm.executeUpdate(insert6);
            stm.executeUpdate(insert7);
            
            
        }catch(SQLException e){
            System.err.println(e);
        }
        
        Thankyou ty = new Thankyou();
        ty.setVisible(true);
        this.setVisible(false);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        rb1.setActionCommand("yes");
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
         rb3.setActionCommand("yes");
    }//GEN-LAST:event_rb3ActionPerformed

    private void rb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb15ActionPerformed
 rb15.setActionCommand("yes");        // TODO add your handling code here:
    }//GEN-LAST:event_rb15ActionPerformed

    private void rb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb12ActionPerformed
 rb12.setActionCommand("no");        // TODO add your handling code here:
    }//GEN-LAST:event_rb12ActionPerformed

    private void rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5ActionPerformed
 rb5.setActionCommand("yes");        // TODO add your handling code here:
    }//GEN-LAST:event_rb5ActionPerformed

    private void rb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6ActionPerformed
 rb6.setActionCommand("no");        // TODO add your handling code here:
    }//GEN-LAST:event_rb6ActionPerformed

    private void rb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb7ActionPerformed
 rb7.setActionCommand("yes");        // TODO add your handling code here:
    }//GEN-LAST:event_rb7ActionPerformed

    private void rb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb8ActionPerformed
 rb8.setActionCommand("no");        // TODO add your handling code here:
    }//GEN-LAST:event_rb8ActionPerformed

    private void rb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb9ActionPerformed
 rb9.setActionCommand("yes");        // TODO add your handling code here:
    }//GEN-LAST:event_rb9ActionPerformed

    private void rb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb10ActionPerformed
 rb10.setActionCommand("no");        // TODO add your handling code here:
    }//GEN-LAST:event_rb10ActionPerformed

    private void rb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb11ActionPerformed
 rb11.setActionCommand("yes");        // TODO add your handling code here:
    }//GEN-LAST:event_rb11ActionPerformed

    private void rb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb13ActionPerformed
 rb13.setActionCommand("yes");        // TODO add your handling code here:
    }//GEN-LAST:event_rb13ActionPerformed

    private void rb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb14ActionPerformed
 rb14.setActionCommand("no");        // TODO add your handling code here:
    }//GEN-LAST:event_rb14ActionPerformed

    private void rb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb16ActionPerformed
 rb16.setActionCommand("no");        // TODO add your handling code here:
    }//GEN-LAST:event_rb16ActionPerformed

    private void rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4ActionPerformed
 rb4.setActionCommand("no");        // TODO add your handling code here:
    }//GEN-LAST:event_rb4ActionPerformed

    private void tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbActionPerformed

   
   

        // TODO add your handling code here:
    }//GEN-LAST:event_tbActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
         rb2.setActionCommand("no"); 
    }//GEN-LAST:event_rb2ActionPerformed

    private void tbKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKeyTyped
char c = evt.getKeyChar();
       if(!(Character.isDigit(c)|| (c == KeyEvent.VK_BACK_SPACE) ||c == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }   
if(tb.getText().length()>=10)
    {
        tb.setText(tb.getText().substring(0, 10));
    }       

// TODO add your handling code here:
    }//GEN-LAST:event_tbKeyTyped

    private void tbPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbPropertyChange



// TODO add your handling code here:
    }//GEN-LAST:event_tbPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MBAQuestionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MBAQuestionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MBAQuestionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MBAQuestionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MBAQuestionnaire().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.ButtonGroup mba1;
    private javax.swing.ButtonGroup mba2;
    private javax.swing.ButtonGroup mba3;
    private javax.swing.ButtonGroup mba4;
    private javax.swing.ButtonGroup mba5;
    private javax.swing.ButtonGroup mba6;
    private javax.swing.ButtonGroup mba7;
    private javax.swing.ButtonGroup mba8;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb11;
    private javax.swing.JRadioButton rb12;
    private javax.swing.JRadioButton rb13;
    private javax.swing.JRadioButton rb14;
    private javax.swing.JRadioButton rb15;
    private javax.swing.JRadioButton rb16;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JRadioButton rb9;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    private javax.swing.JLabel t8;
    private javax.swing.JTextField tb;
    // End of variables declaration//GEN-END:variables
}
